
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# 1. Master node (Control Plane)
- role: control-Plane
  kubeamConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegisteration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPosrt: 443
    protocol: TCP
# 2. Worker node - 리소스 절약
- role: worker